// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "url": "http://www.example.com/support",
            "email": "support@example.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/analytics/": {
            "post": {
                "description": "Возвращает аналитику продаж по указанным параметрам",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Analytics"
                ],
                "summary": "Получить аналитику продаж",
                "parameters": [
                    {
                        "description": "Параметры запроса аналитики",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/structs.AnalyticsSwagger"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешный ответ",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/structs.Analytics"
                            }
                        }
                    },
                    "400": {
                        "description": "Ошибка в запросе"
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера"
                    }
                }
            }
        },
        "/analytics/top/": {
            "get": {
                "description": "Возвращает список складов с наибольшей выручкой",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Analytics"
                ],
                "summary": "Получить топ складов по выручке",
                "responses": {
                    "200": {
                        "description": "Список топовых складов",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/structs.TopAnalytics"
                            }
                        }
                    },
                    "400": {
                        "description": "Ошибка в запросе"
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера"
                    }
                }
            }
        }
    },
    "definitions": {
        "structs.Analytics": {
            "type": "object",
            "properties": {
                "productId": {
                    "description": "Идентификатор товара",
                    "type": "string",
                    "example": "PRD-1001"
                },
                "soldgoods": {
                    "description": "Количество проданных товаров",
                    "type": "integer",
                    "example": 50
                },
                "totalsum": {
                    "description": "Общая сумма продаж",
                    "type": "number",
                    "example": 12500.5
                },
                "warehouseId": {
                    "description": "Идентификатор склада",
                    "type": "string",
                    "example": "WH-001"
                }
            }
        },
        "structs.AnalyticsSwagger": {
            "type": "object",
            "properties": {
                "warehouseId": {
                    "description": "Идентификатор склада",
                    "type": "string",
                    "example": "9be99fa0-2cd1-4c4e-863d-5115095fbd09"
                }
            }
        },
        "structs.TopAnalytics": {
            "description": "Структура данных топовых складов по выручке",
            "type": "object",
            "properties": {
                "addr": {
                    "description": "Адрес склада",
                    "type": "string",
                    "example": "ул. Ленина, 10"
                },
                "totalsum": {
                    "description": "Общая выручка склада",
                    "type": "number",
                    "example": 150000.75
                },
                "warehouseId": {
                    "description": "Идентификатор склада",
                    "type": "string",
                    "example": "WH-001"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http"},
	Title:            "API Go Service",
	Description:      "This is a sample API Go server with Zap logging",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
