// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "url": "http://www.example.com/support",
            "email": "support@example.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/warehouses/add/": {
            "post": {
                "description": "Добавляет новый склад в систему складирования",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Склады"
                ],
                "summary": "Добавить новый склад",
                "parameters": [
                    {
                        "description": "Данные склада",
                        "name": "warehouse",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/structs.WarehousesSwagger"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Склад успешно добавлен"
                    },
                    "400": {
                        "description": "Некорректные входные данные"
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера"
                    }
                }
            }
        },
        "/warehouses/all/": {
            "get": {
                "description": "Возвращает список всех складов в системе",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Склады"
                ],
                "summary": "Получить все склады",
                "responses": {
                    "200": {
                        "description": "Список складов",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/structs.Warehouses"
                            }
                        }
                    },
                    "400": {
                        "description": "Ошибка запроса"
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера"
                    }
                }
            }
        }
    },
    "definitions": {
        "structs.Warehouses": {
            "type": "object",
            "properties": {
                "addr": {
                    "description": "Физический адрес склада",
                    "type": "string",
                    "example": "ул. Складская, д.1"
                },
                "id": {
                    "description": "Уникальный идентификатор склада",
                    "type": "integer",
                    "example": 1
                },
                "warehouseId": {
                    "description": "Внешний идентификатор склада",
                    "type": "string",
                    "example": "WH-001"
                }
            }
        },
        "structs.WarehousesSwagger": {
            "type": "object",
            "properties": {
                "addr": {
                    "type": "string",
                    "example": "fghverv4446"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "/api/v1",
	Schemes:          []string{"http"},
	Title:            "API Go Service",
	Description:      "This is a sample API Go server with Zap logging",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
